### PR TITLE
Fix/review

### PR DESCRIPTION
**Pull request by Kiefna**
Creating .gitignore, small code changes all around.
We will review it together.

### CODE REVIEW

**Comment by mugabiisaac** [comment]
thanks chris, let me log in in just 30min

**Comment by Kiefna** [comment]
Haha no worries, that was just an automatic email GitHub sends out, we will still review together when we have our meeting. See you then.

**Review by mugabiisaac — APPROVED** [review]
thanks, approved

**Comment by mugabiisaac** [comment]
great

**Comment by mugabiisaac** [comment]
hello Chris,
there's just one more thing we didnt discuss into detail,
that's to do with depopulating my templates with so much html and working
more with blocks,

regards

**Pull request merged**
